server:
  port: 8889
spring:
  application:
    name: smxr-cloud-gateway
  cloud:
    consul:
      discovery:
        enabled: true
        register: true
        ip-address: 127.0.0.1
        prefer-ip-address: true
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: smxr-spring-cloud-22
          uri: lb://smxr-spring-cloud-22
          predicates:
            - Path=/test22/**
        - id: smxr-spring-cloud-33
          uri: lb://smxr-spring-cloud-33
          predicates:
            - Path=/test33/**
        - id: openfeign
          uri: lb://openfeign
          predicates:
            - Path=/api/**
management:
  endpoints:
    web:
      exposure:
        include: "*"
