server:
  port: 8083
#  port: 8081
#  port: 8082
spring:
  application:
    name: smxr-spring-cloud-22
  cloud:
    consul:
      port: 8500
      host: 127.0.0.1
      discovery:
        enabled: true
        register: true
        ip-address: 127.0.0.1
        prefer-ip-address: true
